spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        show_sql: true
        highlight_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      password:


jwt:
  header: Authorization
  secret: dGhpcyBpcyBteSBoaWRkZW4gand0IHNlY3JldCBrZXksIHdoYXQgaXMgeW91ciBqd3Qgc2VjcmV0IGtleT9YWA==
  access-token-validity-in-seconds: 3600000

logging:
  level:
    org:
      springframework:
        security: DEBUG
